### ISSUE TITLE
使用l515传感器复现

### ISSUE THREAD

**Issue by xhgxh** [hku-mars/FAST-LIVO2#195]
![Image](https://github.com/user-attachments/assets/553a9e5f-c339-461f-ae3e-ba8245fa2d33)

你好，郑博，我在配置文件和参数都替换后，LIO和VIO都出现No point的情况，如上图，但是点云数据和图像数据都是有的，如下图所是。请问一下我是哪个步骤出现了问题吗。

![Image](https://github.com/user-attachments/assets/732d8949-f6b6-447e-9fe7-67042386e08b)

**Comment by xuankuzcr** [comment]
你的数据可以分享给我下，我帮你看看

**Comment by nit-xhg** [comment]
> 你的数据可以分享给我下，我帮你看看
感谢！请问是参数还是传感器数据呢，请问可以给我个你的邮箱吗

**Comment by ErcBunny** [comment]
郑博 @xuankuzcr 您好！我有类似的问题想请教一下 。

我使用了一个类似L515的传感器（噪声比较大，最大量程2.5m左右，标定结果在[这里](https://drive.google.com/file/d/1mE6I2LN7I9eVmZ7p1V2uY3DI5F9QDaRb/view?usp=drive_link)，且可以认为Lidar frame和cam frame是一致的），正在试图运行LIVO2在自己的[数据集](https://drive.google.com/file/d/1o9LirEnLpqiOlSnMlPIt9dwvlKuq4idY/view?usp=drive_link)上，但是不成功。

https://github.com/user-attachments/assets/3e2572a1-c23a-418f-8db5-9dec0cb16751

相机配置文件我是这么写的：

```yaml
cam_model: Pinhole
cam_width: 320
cam_height: 240
scale: 0.5 # 这是什么？没改
cam_fx: 227.46204253
cam_fy: 227.42116608
cam_cx: 159.92612471
cam_cy: 120.20147916
cam_d0: 0.03141088 # 应该是k1？
cam_d1: -0.09764829 # k2？
cam_d2: -0.00008679 # p1？
cam_d3: -0.00000261 # p2？
```

其他配置是从avia抄过来的，只改动了topic，TF，和lidar type：

```yaml
common:
  img_topic: "/dolphin/image/ir/processed"
  lid_topic: "/dolphin/pcd/processed"
  imu_topic: "/wit/imu"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [0.0442646, -0.00314331, -0.03111024] # translation of LiDAR frame w.r.t. IMU frame
  extrinsic_R: [0.00505849, -0.99981994, 0.01828918,
                -0.9999717, -0.00495573, 0.00565979,
                -0.00556814, -0.0183173, -0.99981672] # rotation matrix of LiDAR frame w.r.t. IMU frame
  Rcl: [1, 0, 0, 0, 1, 0, 0, 0, 1] # rotation matrix of LiDAR frame w.r.t. Camera frame
  Pcl: [0.04165, 0.02326, -0.0284] # translation of LiDAR frame w.r.t. Camera frame

time_offset: 
  imu_time_offset: 0.0
  img_time_offset: 0.0
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 1
  filter_size_surf: 0.1
  lidar_type: 4 # L515
  scan_line: 6
  blind: 0.8

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.5 # 0.2
  gyr_cov: 0.3 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0025 # 0.005
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:  
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: true
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "CBD_Building_01"
  pose_output_en: false

pcd_save:
  pcd_save_en: false
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
```

这里问题是什么？是参数没设置对（BTW参数的意义在哪儿可以找到）？还是点云质量太差了？

期待您的答复！
