### ISSUE TITLE
[ERROR] "in vk::PinholeCamera::world2cam(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&)"

### ISSUE THREAD

**Issue by FaterYU** [hku-mars/FAST-LIVO2#264]
郑博您好！我在使用 mid360 + realsense d435i 在复现时遇到以下问题，但奇怪的是，我刚开始第一次配好环境后是可以正常运行的，但在刷了系统重新配的时候出现了这个问题，有点怀疑是不是哪个依赖的版本过新了，我有点定位不出来。

运行报错：

```zsh
[fastlivo_mapping-4] [ LIO ] Raw feature num: 2965, downsampled feature num:1154 effective feature num: 992 average residual: 0.0202108
[fastlivo_mapping-4] [ LIO ] Raw feature num: 2965, downsampled feature num:1154 effective feature num: 994 average residual: 0.020905
[fastlivo_mapping-4] [ LIO ] Raw feature num: 2965, downsampled feature num:1154 effective feature num: 994 average residual: 0.0209072
[fastlivo_mapping-4] [ LIO ] Raw feature num: 2965, downsampled feature num:1154 effective feature num: 994 average residual: 0.0209072
[fastlivo_mapping-4] [ LIO ] Update Voxel Map
[fastlivo_mapping-4] +-------------------------------------------------------------+
[fastlivo_mapping-4] |                         LIO Mapping Time                    |
[fastlivo_mapping-4] +-------------------------------------------------------------+
[fastlivo_mapping-4] | Algorithm Stage               | Time (secs)                 |
[fastlivo_mapping-4] +-------------------------------------------------------------+
[fastlivo_mapping-4] | DownSample                    | 0.000132                    |
[fastlivo_mapping-4] | ICP                           | 0.001914                    |
[fastlivo_mapping-4] | updateVoxelMap                | 0.000588                    |
[fastlivo_mapping-4] +-------------------------------------------------------------+
[fastlivo_mapping-4] | Current Total Time            | 0.004448                    |
[fastlivo_mapping-4] | Average Total Time            | 0.004448                    |
[fastlivo_mapping-4] +-------------------------------------------------------------+
[fastlivo_mapping-4] [INFO] [1745852210.358399502] [laserMapping]: get imu at time: 1745852210.355606
[fastlivo_mapping-4] got imu: 1.74585e+09 imu size 3
[fastlivo_mapping-4] [INFO] [1745852210.361486610] [laserMapping]: get imu at time: 1745852210.361320
[fastlivo_mapping-4] got imu: 1.74585e+09 imu size 4
[fastlivo_mapping-4] [INFO] [1745852210.365685919] [laserMapping]: get imu at time: 1745852210.365592
[fastlivo_mapping-4] got imu: 1.74585e+09 imu size 5
[fastlivo_mapping-4] [INFO] [1745852210.371484675] [laserMapping]: get imu at time: 1745852210.371313
[fastlivo_mapping-4] got imu: 1.74585e+09 imu size 6
[fastlivo_mapping-4] [INFO] [1745852210.373493126] [laserMapping]: Get LiDAR, its header time: 1745852210.353577
[fastlivo_mapping-4] [INFO] [1745852210.373506810] [laserMapping]: get point cloud at time: 1745852210.353577
[fastlivo_mapping-4] [ Preprocess ] Input point number: 3936
[fastlivo_mapping-4] [ Preprocess ] Output point number: 1114
[fastlivo_mapping-4] [ VIO ] Raw feature num: 2965
[ERROR] [fastlivo_mapping-4]: process has died [pid 46088, exit code -11, cmd '/home/mobot/ws_nav/install/fast_livo/lib/fast_livo/fastlivo_mapping --ros-args -r __node:=laserMapping --params-file /home/mobot/ws_nav/install/mobot_bringup/share/mobot_bringup/config/fastlivo_mid360.yaml --params-file /home/mobot/ws_nav/install/mobot_bringup/share/mobot_bringup/config/fastlivo_camera_pinhole_mid360.yaml -r /aft_mapped_to_init:=/Odometry'].
```

`GDB` 信息：

```zsh
Thread 1 "fastlivo_mappin" reveived signal SIGSEGV, Segmentation fault.
#0  0x00007ffff7d48289 in vk::PinholeCamera::world2cam(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&) const ()
    at /home/mobot/ws_nav/install/vikit_common/lib/libvikit_common.so
(gdb) bt
#0  0x00007ffff7d48289 in vk::PinholeCamera::world2cam(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&) const ()
    at /home/mobot/ws_nav/install/vikit_common/lib/libvikit_common.so
#1  0x000055555565f1ea in VIOManager::generateVisualMapPoints(cv::Mat, std::vector<pointWithVar, std::allocator<pointWithVar> >&) ()
#2  0x0000555555668f09 in VIOManager::processFrame(cv::Mat&, std::vector<pointWithVar, std::allocator<pointWithVar> >&, std::unordered_map<VOXEL_LOCATION, VoxelOctoTree*, std::hash<VOXEL_LOCATION>, std::equal_to<VOXEL_LOCATION>, std::allocator<std::pair<VOXEL_LOCATION const, VoxelOctoTree*> > > const&, double) ()
#3  0x00005555555aadcd in LIVMapper::handleVIO() ()
#4  0x00005555555b3852 in LIVMapper::run(std::shared_ptr<rclcpp::Node>&) ()
#5  0x000055555558afb0 in main ()
```

- `eigen3`: 3.4.90
- `opencv4`: 4.5.4

看起来是 `frame.h` 里的

```cpp
/// Transforms point coordinates in world-frame (w) to camera pixel
  /// coordinates (c).
  inline Vector2d w2c(const Vector3d &xyz_w) const {
    return cam_->world2cam(T_f_w_ * xyz_w);
  }
```

这个内联函数的 `world2cam` 传递的参数类型不是定义的 `Vector3d`，但我在用 `Vector3d{ T_f_w_ * xyz_w }` 替换强制指定类型也是同样的gdb信息。`T_f_w_ * xyz_w` 这个的类型我看的是 `N5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEE`，不知道为什么不是 `Vector3d`。我之前正常运行过一次，怀疑过是 `eigen` 的版本，我降回 `3.3.4` 还是一样的报错。

我的参数文件如下：
`fastlivo_camera_pinhole_mid360.yaml`:

```yaml
/**:
  ros__parameters:
    camera:
      model: Pinhole
      width: 1280
      height: 720
      scale: 1.0
      fx: 902.2940673828125
      fy: 900.98583984375
      cx: 640.0183715820312
      cy: 378.0950927734375
      d0: -0.076160
      d1: 0.123001
      d2: -0.00113
      d3: 0.000251
```

`fastlivo_mid360.yaml`:

```yaml
/**:
  ros__parameters:
    common:
      img_topic: "/realsense_camera/realsense_camera/color/image_raw"
      lid_topic: "/livox/lidar"
      imu_topic: "/livox/imu"
      img_en: 1
      lidar_en: 1
      ros_driver_bug_fix: false

    extrin_calib:
      # imu 2 lidar
      extrinsic_T: [0.011, 0.02329, -0.04412]
      extrinsic_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      # Rcl: [-0.34925,-0.92811,-0.12899,
      #       0.36735,-0.00898,-0.93004,
      #       0.86202,-0.37220,0.34408] 
      # Pcl: [-0.01363,-0.14069,-0.16574]
      # lidar 2 camera
      Rcl: [0.799, 0.0, -0.602, 0.0, 1.0, 0.0, 0.602, 0.0, 0.799]
      Pcl: [0.07, 0.0, -0.001]


    time_offset:
      imu_time_offset: 0.0
      img_time_offset: 0.1
      exposure_time_init: 0.0

    preprocess:
      point_filter_num: 1
      filter_size_surf: 0.1
      lidar_type: 1 # Livox Avia LiDAR
      scan_line: 4
      blind: 0.5

    vio:
      max_iterations: 5
      outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
      img_point_cov: 100 # 100 1000
      patch_size: 8
      patch_pyrimid_level: 4
      normal_en: true
      raycast_en: false
      inverse_composition_en: false
      exposure_estimate_en: true
      inv_expo_cov: 0.1

    imu:
      imu_en: true
      imu_int_frame: 30
      acc_cov: 0.8 # 0.2
      gyr_cov: 0.5 # 0.5
      b_acc_cov: 0.001 # 0.1
      b_gyr_cov: 0.001 # 0.1

    lio:
      max_iterations: 5
      dept_err: 0.02
      beam_err: 0.15
      min_eigen_value: 0.005 # 0.005
      voxel_size: 0.5
      max_layer: 2
      max_points_num: 50
      layer_init_num: [5, 5, 5, 5, 5]

    local_map:
      map_sliding_en: false
      half_map_size: 100
      sliding_thresh: 8.0

    uav:
      imu_rate_odom: false
      gravity_align_en: true

    publish:
      dense_map_en: true
      pub_effect_point_en: false
      pub_plane_en: false
      pub_scan_num: 1
      blind_rgb_points: 0.0

    evo:
      seq_name: "CBD_Building_01"
      pose_output_en: false

    pcd_save:
      pcd_save_en: true
      colmap_output_en: true # need to set interval = -1
      filter_size_pcd: 0.15
      interval: -1
```
