### ISSUE TITLE
关于大尺度实验数据集的问题

### ISSUE THREAD

**Issue by jiangcheng0128** [hku-mars/FAST-LIVO2#313]
您好，郑博！感谢开源这么优秀的工作。以下是我关于数据集的问题，等您有时间希望可以回复一下。

**问题：**当前，我们正在实验大场景数据集（总长度大概4公里多，一圈下来中间没有交叉）下的定位表现，发现起始和终点位置**z轴偏移有20多米。**

**硬件组合：**我们采用的是mid360和flir blackfly s usb3组合的手持设备。

**当前的产生大偏移的猜测：**

（1）数据集录制过程全程手持，会有一些比较大的抖动，这会影响实验效果吗？是不是需要使用无人机或者小车更稳定一些？

（2）数据集录制初始并没有静置，这对结果影响大吗？

（3）对于大场景参数设置需要调参，我参考您之前回答的问题，  需要微调这三个参数：acc_cov, gyr_cov, voxel_size。另外关于局部地图参数map_sliding_en，大场景下设为false，结果会差一些。但如果设为true，会内存爆炸。

（4）在vio部分，我们发现当走的过快的时候，视觉特征点会变得特别少，甚至完全消失，这对结果影响有多大？录制数据包的过程速度大约多少是合适的？我们当前的帧率是每秒10帧。

我们给出参数文件供参考，期待您的答复，谢谢！

```yaml
common:
  img_topic: "/camera/image_color/compressed"
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [-0.011, -0.02329, 0.04412]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  #Rcl: [ 0.00133371, -0.99999809, -0.0014312,
  #       0.57221313, -0.00041057, -0.82010485,
  #       0.82010387, 0.00191283, 0.57221148]
  #Pcl: [0.00369193925, -0.0956633082, -0.0242751396]
  Rcl: [ 0.00558967, -0.99997282, -0.00480859,
         0.58352373, 0.00716679, -0.81206446,
         0.81207685, 0.00173324, 0.58354793 ]
  Pcl: [0.0164, -0.0868, -0.0181]

time_offset:
  imu_time_offset: 0.0
  img_time_offset: 0.1
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 1
  filter_size_surf: 0.1
  lidar_type: 1 # Livox Avia LiDAR
  scan_line: 6 # 6
  blind: 0.8 # 0.8

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.5 #0.5 ， 0.0138
  gyr_cov: 0.3 #0.3 ， 0.0021
  b_acc_cov: 0.0001  # 0.0001
  b_gyr_cov: 0.0001 # 0.0001

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0025 # 0.005
  voxel_size: 1.0
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: true
  pub_effect_point_en: false
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "tsinghua01"
  pose_output_en: true

pcd_save:
  pcd_save_en: false #false
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

```
